### ISSUE TITLE
DB error if no player has join game

### ISSUE THREAD

**Issue by natcoso9955** [ChrisAshtear/Zomboid-Server-Stats-Reporter#1]
Hi, i am working on implementing this on my Unraid server, via your 4 docker images.
just wanted to highlight an error in your reporter in reportServerData.php on line 43. If no player has connected to the game yet, $d is not defined which then means when it try to closesql it fails as $d doesnt exist.

**Comment by ChrisAshtear** [comment]
this specific error was resolved by natcoso, and also added try/catches and provided a more detailed error letting the user know that a player needs to be in the server to create the save files. closing
